[package]
name = "uiexplore2"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
eframe = "0.29.1"
egui_extras = { version = "0.29.1", features = ["all_loaders"] }
env_logger = "0.11.5"
socarel = "0.4.0"
uiautomation = "0.13.4"
